# Generated by Django 2.2 on 2020-06-12 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_label', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('operation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available', models.BooleanField(blank=True, null=True)),
                ('dateOfEntry', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiryDate', models.DateTimeField(blank=True, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('company_of_origin', models.CharField(blank=True, max_length=500, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=500, null=True)),
                ('Product_Label', models.ManyToManyField(blank=True, related_name='label', to='shop.label')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('dateOfEntry', models.DateTimeField(auto_now_add=True)),
                ('expiryDate', models.DateTimeField()),
                ('size', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('company_of_origin', models.CharField(blank=True, max_length=500)),
                ('country_of_origin', models.CharField(blank=True, max_length=500)),
                ('Product_Labels', models.ManyToManyField(blank=True, related_name='final_label', to='shop.label')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_products', to='shop.Product_SubCategory')),
            ],
        ),
    ]
